$ANSIBLE_VAULT;1.1;AES256
61346563363165333863386365643534633832353736333162643061653230366635646163626131
3630306532316535383664396234383061653337383939620a393731316164363661613631613761
32616163633639646639616438333931346439366266633163353463336466303465333733626264
3330663061626233370a386562633166626565323635316261343865373634666332393439313866
35623966303438653931306165333066336162386161303238663239663132383264663064313338
3461336533643830303532343164366230643939396665353933
