apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-app-ocp
  namespace: test
spec:
  rules:
  - host: bss1.apps.devocp1-416.sktelecom.com
    http:
      paths:
      - path: /test1
        pathType: Prefix
        backend:
          service:
            name: test-nginx-app-ocp
            port:
              number: 8080
      - path: /test2
        pathType: Prefix
        backend:
          service:
            name: test-nginx-app-ocp
            port:
              number: 8080
