$ANSIBLE_VAULT;1.1;AES256
65373861306132386565313037656466306430343734626531313366383766376632323231336537
6336363066643534383762306435376163633961376266330a346334346464663862313638396466
31346164343632303064303536396165393538316630313861383266323533613635363062623236
3364636538303162620a313639386365343963363761343339393862363662633666393534323838
65353534643039303334656565353663656566373135326230323733623235636335393764383465
30646262386262663734393836373532616536313432666661663964636138373834306235343236
65343835313330316265323234623761393361376239636431303139336634376136306634636236
63333336313562303764306166303032353565336532326565646634363735643037383137623664
66323537316165623538346331656538376561353934353363643433393734373438
