apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-busybox
spec:
  serviceName: "test-busybox"
  replicas: 3
  selector:
    matchLabels:
      app: test-busybox
  template:
    metadata:
      labels:
        app: test-busybox
    spec:
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      containers:
      - name: busybox
        image: registry.bss-ocp.sktelecom.com:5000/test/busybox:latest
        command:
          - sh
          - -c
          - "sleep 3600"
        volumeMounts:
        - name: data
          mountPath: /mnt/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: managed-nfs-storage
      resources:
        requests:
          storage: 1Gi
