kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-nfs-pod
    image: skt-bssocpdargst.devocp1-416.sktelecom.com:5018/test/busybox:latest
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
